source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HYStorage_Example', :exclusive => true do
  pod 'HYStorage', :path => '../'
end

target 'HYStorage_Tests', :exclusive => true do
  pod 'HYStorage', :path => '../'

  
end
